name: ttsectrack
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  permission_handler: ^12.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  mocktail: ^1.0.4
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  geolocator: ^14.0.2
  intl: ^0.20.2
  sqflite: ^2.4.2
  bloc: ^9.0.0
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  geocoding: ^2.1.1
  dio: ^5.8.0+1
  device_info_plus: ^11.5.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/MobitraLogo.png
    - lib/assets/images/logo.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/MobitraLogo.png"
  generate: true
